import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  TreePine,
  Sprout,
  Leaf,
  Heart,
  Phone,
  CheckCircle2,
  Bird,
  Fish,
  MapPin,
  Users,
  Droplets,
  Share2,
  Copy,
  MessageCircle,
  Star,
} from 'lucide-react';

// Remote images (generated by Gemini and uploaded to Firebase Storage)
const BASE = 'https://storage.googleapis.com/monaco-community.firebasestorage.app/donaton';
const IMG = {
  hero: `${BASE}/hero-cienaga.png`,
  jaguar: `${BASE}/jaguar.png`,
  manatee: `${BASE}/manatee.png`,
  capybara: `${BASE}/capybara.png`,
  turpial: `${BASE}/turpial-bird.png`,
  caiman: `${BASE}/caiman.png`,
  planting: `${BASE}/tree-planting.png`,
  aerial: `${BASE}/aerial-wetland.png`,
};

const PHONES = [
  { display: '315 787 1935', raw: '573157871935' },
  { display: '312 648 3739', raw: '573126483739' },
  { display: '311 865 4130', raw: '573118654130' },
];

const BENEFITS = [
  {
    icon: TreePine,
    title: 'Dona un árbol',
    desc: 'Tu aporte se convierte en un árbol nativo que se siembra en la Ciénaga de Barbacoas.',
  },
  {
    icon: Sprout,
    title: 'Haz seguimiento a su crecimiento',
    desc: 'Recibirás actualizaciones con fotos del crecimiento y salud de tu árbol.',
  },
  {
    icon: Heart,
    title: 'Construyamos vida juntos',
    desc: 'Cada árbol restaura el hábitat de manatíes, jaguares, caimanes, aves y cientos de especies.',
  },
];

const WILDLIFE = [
  { img: IMG.jaguar, name: 'Jaguar', fact: 'El gran felino de la Amazonía colombiana, en peligro crítico.', icon: Star },
  { img: IMG.manatee, name: 'Manatí antillano', fact: 'Pacífico gigante de agua dulce, símbolo de la ciénaga.', icon: Fish },
  { img: IMG.capybara, name: 'Capibara', fact: 'El roedor más grande del mundo, abundante en los humedales.', icon: Leaf },
  { img: IMG.turpial, name: 'Turpial', fact: 'Ave nacional de Colombia, símbolo de libertad.', icon: Bird },
  { img: IMG.caiman, name: 'Caimán aguja', fact: 'Reptil centinela del ecosistema, esencial para el equilibrio.', icon: Droplets },
];

export function Donaton() {
  const [copied, setCopied] = useState(false);
  const [treesCount, setTreesCount] = useState(1247);

  // Fake live counter (just for vibe)
  useEffect(() => {
    const t = setInterval(() => {
      if (Math.random() < 0.4) setTreesCount((n) => n + 1);
    }, 4000);
    return () => clearInterval(t);
  }, []);

  const share = async () => {
    const url = window.location.href;
    const text = 'Ayúdame a salvar la Ciénaga de Barbacoas 🌳 Dona un árbol:';
    if (navigator.share) {
      try {
        await navigator.share({ title: 'Gran Donatón Ambiental', text, url });
        return;
      } catch { /* user cancelled */ }
    }
    try {
      await navigator.clipboard.writeText(`${text} ${url}`);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch { /* ignore */ }
  };

  const whatsappLink = (phone: string) =>
    `https://wa.me/${phone}?text=${encodeURIComponent('Hola, quiero donar un árbol para la Ciénaga de Barbacoas 🌳')}`;

  return (
    <div className="min-h-screen bg-gradient-to-b from-emerald-950 via-emerald-900 to-emerald-950 text-white overflow-x-hidden">
      {/* ────────── HERO ────────── */}
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
        <div className="absolute inset-0">
          <img
            src={IMG.hero}
            alt="Ciénaga de Barbacoas"
            className="absolute inset-0 w-full h-full object-cover"
            onError={(e) => ((e.currentTarget as HTMLImageElement).style.display = 'none')}
          />
          {/* Gradient overlays */}
          <div className="absolute inset-0 bg-gradient-to-b from-emerald-950/70 via-emerald-900/40 to-emerald-950" />
          <div className="absolute inset-0 bg-gradient-to-r from-black/60 via-transparent to-black/60" />
        </div>

        {/* Floating leaves */}
        {Array.from({ length: 15 }).map((_, i) => (
          <motion.div
            key={i}
            className="absolute pointer-events-none"
            style={{ left: `${(i * 37) % 100}%`, top: `-5%` }}
            animate={{
              y: ['0vh', '110vh'],
              x: [0, Math.sin(i) * 100],
              rotate: [0, 360],
            }}
            transition={{
              duration: 12 + (i % 5) * 2,
              repeat: Infinity,
              delay: i * 0.5,
              ease: 'linear',
            }}
          >
            <Leaf className="h-4 w-4 text-emerald-400/40" />
          </motion.div>
        ))}

        <div className="relative z-10 container mx-auto px-4 text-center py-20">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1 }}
          >
            <div className="inline-flex items-center gap-2 rounded-full bg-amber-500/20 border border-amber-400/40 px-4 py-1.5 text-[11px] font-bold uppercase tracking-[0.25em] text-amber-200 mb-6 backdrop-blur-sm">
              <MapPin className="h-3 w-3" />
              Yondó · Antioquia · Colombia
            </div>
            <h1
              className="font-serif font-black tracking-tight leading-none mb-3"
              style={{ fontFamily: 'Georgia, "Times New Roman", serif' }}
            >
              <span className="block text-5xl sm:text-7xl md:text-8xl lg:text-9xl text-white drop-shadow-2xl">
                GRAN
              </span>
              <span className="block text-5xl sm:text-7xl md:text-8xl lg:text-9xl text-white drop-shadow-2xl">
                DONATÓN
              </span>
              <span className="block text-xl sm:text-3xl md:text-4xl text-amber-300 mt-2 tracking-[0.2em]">
                AMBIENTAL
              </span>
            </h1>
            <motion.p
              className="mt-8 text-2xl sm:text-3xl md:text-5xl italic font-serif text-amber-200"
              style={{ fontFamily: 'Georgia, serif' }}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.5, duration: 1 }}
            >
              Ciénaga Barbacoas
              <span className="block text-xl sm:text-2xl md:text-3xl text-white/90 mt-2">
                te necesita
              </span>
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 1, duration: 0.8 }}
              className="mt-12 flex flex-col sm:flex-row gap-3 justify-center"
            >
              <a href="#donar">
                <button className="group inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-amber-500 to-amber-400 hover:from-amber-400 hover:to-amber-300 text-emerald-950 font-black px-10 py-4 text-base shadow-2xl shadow-amber-500/40 transition-all hover:scale-105">
                  <TreePine className="h-5 w-5" />
                  DONA UN ÁRBOL
                  <Heart className="h-4 w-4 fill-emerald-950 group-hover:animate-pulse" />
                </button>
              </a>
              <button
                onClick={share}
                className="inline-flex items-center gap-2 rounded-full bg-white/10 hover:bg-white/20 border border-white/20 backdrop-blur-md text-white font-bold px-8 py-4 text-sm transition"
              >
                {copied ? <CheckCircle2 className="h-4 w-4" /> : <Share2 className="h-4 w-4" />}
                {copied ? '¡Copiado!' : 'Compartir'}
              </button>
            </motion.div>

            {/* Live tree counter */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1.5, duration: 1 }}
              className="mt-14 inline-flex items-center gap-3 rounded-2xl bg-emerald-950/50 backdrop-blur-md border border-emerald-400/20 px-6 py-3"
            >
              <div className="relative">
                <TreePine className="h-6 w-6 text-emerald-400" />
                <span className="absolute -top-1 -right-1 flex h-2 w-2">
                  <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75"></span>
                  <span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-400"></span>
                </span>
              </div>
              <div className="text-left">
                <p className="text-[10px] uppercase tracking-widest text-emerald-300 font-bold">
                  Árboles donados
                </p>
                <AnimatePresence mode="popLayout">
                  <motion.p
                    key={treesCount}
                    initial={{ opacity: 0, y: -10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: 10 }}
                    className="text-2xl font-black text-white tabular-nums"
                  >
                    {treesCount.toLocaleString('es-CO')}
                  </motion.p>
                </AnimatePresence>
              </div>
            </motion.div>
          </motion.div>
        </div>

        {/* Scroll down */}
        <motion.div
          className="absolute bottom-8 left-1/2 -translate-x-1/2 text-white/60 text-[10px] uppercase tracking-[0.3em]"
          animate={{ y: [0, 8, 0] }}
          transition={{ duration: 2, repeat: Infinity }}
        >
          ↓ Desplázate
        </motion.div>
      </section>

      {/* ────────── CALL ────────── */}
      <section className="relative py-20 md:py-28">
        <div className="container mx-auto px-4 max-w-4xl text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
          >
            <div className="inline-flex items-center gap-2 rounded-full bg-emerald-500/15 border border-emerald-400/30 px-4 py-1.5 text-xs font-bold uppercase tracking-[0.25em] text-emerald-300 mb-6">
              <Sprout className="h-3 w-3" />
              El momento es ahora
            </div>
            <h2 className="text-3xl md:text-5xl font-bold mb-6 leading-tight">
              La naturaleza nos necesita<br />
              <span className="text-amber-300">hoy más que nunca.</span>
            </h2>
            <p className="text-xl md:text-2xl text-emerald-100 leading-relaxed">
              Es momento de <strong className="text-amber-300">actuar</strong> y{' '}
              <strong className="text-amber-300">dejar huella</strong>.
            </p>
            <p className="mt-8 text-2xl md:text-4xl font-serif italic text-emerald-200" style={{ fontFamily: 'Georgia, serif' }}>
              Dona un árbol y sé parte del <span className="text-amber-300">cambio</span>.
            </p>
          </motion.div>
        </div>
      </section>

      {/* ────────── BENEFITS ────────── */}
      <section className="relative py-20 bg-gradient-to-b from-transparent to-emerald-950">
        <div className="container mx-auto px-4 max-w-6xl">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {BENEFITS.map((b, i) => {
              const Icon = b.icon;
              return (
                <motion.div
                  key={b.title}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.6, delay: i * 0.15 }}
                  className="group relative rounded-3xl bg-gradient-to-br from-emerald-800/50 to-emerald-900/50 backdrop-blur-sm border border-emerald-400/20 p-7 hover:border-amber-400/40 hover:shadow-2xl hover:shadow-emerald-500/20 transition-all"
                >
                  <div className="h-14 w-14 rounded-2xl bg-gradient-to-br from-amber-500 to-emerald-600 flex items-center justify-center mb-5 shadow-lg group-hover:scale-110 transition-transform">
                    <Icon className="h-7 w-7 text-white" />
                  </div>
                  <h3 className="text-xl font-bold mb-2 text-white">{b.title}</h3>
                  <p className="text-sm text-emerald-100/80 leading-relaxed">{b.desc}</p>
                </motion.div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ────────── WILDLIFE ────────── */}
      <section className="relative py-20">
        <div className="container mx-auto px-4 max-w-6xl">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className="text-center mb-14"
          >
            <p className="text-xs font-bold uppercase tracking-[0.3em] text-amber-400 mb-3">
              El tesoro que protegemos
            </p>
            <h2 className="text-3xl md:text-5xl font-bold tracking-tight">
              Vida silvestre de la Ciénaga
            </h2>
          </motion.div>

          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
            {WILDLIFE.map((w, i) => (
              <motion.div
                key={w.name}
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                className="group relative overflow-hidden rounded-2xl aspect-[4/5] cursor-pointer"
              >
                <img
                  src={w.img}
                  alt={w.name}
                  className="absolute inset-0 w-full h-full object-cover group-hover:scale-110 transition-transform duration-700"
                  onError={(e) => {
                    (e.currentTarget as HTMLImageElement).style.background =
                      'linear-gradient(135deg, #064e3b, #022c22)';
                  }}
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black via-black/30 to-transparent" />
                <div className="absolute bottom-0 left-0 right-0 p-4">
                  <p className="text-[10px] uppercase tracking-widest text-amber-300 font-bold mb-1">
                    {w.name}
                  </p>
                  <p className="text-xs text-white/80 line-clamp-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    {w.fact}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ────────── IMPACT NUMBERS ────────── */}
      <section className="relative py-20 bg-gradient-to-br from-emerald-900 via-emerald-800 to-emerald-900 border-y border-emerald-700/50">
        <div className="absolute inset-0 overflow-hidden">
          <img src={IMG.aerial} alt="" className="w-full h-full object-cover opacity-20" />
        </div>
        <div className="container mx-auto px-4 max-w-6xl relative">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-5">
            {[
              { n: '9.500', label: 'Hectáreas', sub: 'de humedal protegido' },
              { n: '250+', label: 'Especies', sub: 'de fauna endémica' },
              { n: '1.200+', label: 'Familias', sub: 'de la comunidad' },
              { n: '100%', label: 'Nativo', sub: 'árboles sembrados' },
            ].map((s, i) => (
              <motion.div
                key={s.label}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                className="text-center rounded-2xl bg-black/30 backdrop-blur-md border border-emerald-400/20 p-5"
              >
                <p className="text-3xl md:text-5xl font-black text-amber-300 tracking-tight">{s.n}</p>
                <p className="text-xs uppercase tracking-widest text-white font-bold mt-2">{s.label}</p>
                <p className="text-[11px] text-emerald-200 mt-1">{s.sub}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ────────── DONATE CTA ────────── */}
      <section id="donar" className="relative py-20 md:py-28">
        <div className="container mx-auto px-4 max-w-5xl">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className="relative overflow-hidden rounded-3xl"
          >
            <img src={IMG.planting} alt="" className="absolute inset-0 w-full h-full object-cover" />
            <div className="absolute inset-0 bg-gradient-to-r from-emerald-950/95 via-emerald-900/85 to-emerald-950/95" />

            <div className="relative p-8 md:p-12 text-center">
              <Heart className="h-10 w-10 text-amber-400 fill-amber-400 mx-auto mb-4" />
              <h2 className="text-3xl md:text-5xl font-bold mb-4 tracking-tight">
                ¡Cada árbol cuenta,<br />
                <span className="text-amber-300">cada aporte suma!</span>
              </h2>
              <p className="text-base md:text-lg text-emerald-100 max-w-xl mx-auto mb-10">
                Escríbenos por WhatsApp y te guiamos paso a paso para hacer tu donación segura y
                certificada.
              </p>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 max-w-3xl mx-auto">
                {PHONES.map((p) => (
                  <a
                    key={p.raw}
                    href={whatsappLink(p.raw)}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="group rounded-2xl bg-gradient-to-br from-emerald-600 to-emerald-800 hover:from-emerald-500 hover:to-emerald-700 p-5 transition-all hover:scale-105 shadow-lg shadow-emerald-900/50"
                  >
                    <div className="flex items-center justify-center gap-2 mb-2">
                      <MessageCircle className="h-5 w-5 text-green-300" />
                      <span className="text-[10px] uppercase tracking-widest font-bold text-emerald-100">
                        WhatsApp
                      </span>
                    </div>
                    <p className="text-xl font-black text-white font-mono">{p.display}</p>
                  </a>
                ))}
              </div>

              <div className="mt-8 flex flex-wrap justify-center gap-3 text-xs text-emerald-200">
                <span className="inline-flex items-center gap-1.5 rounded-full bg-white/5 border border-white/10 px-3 py-1">
                  <CheckCircle2 className="h-3 w-3 text-amber-300" />
                  Donación certificada
                </span>
                <span className="inline-flex items-center gap-1.5 rounded-full bg-white/5 border border-white/10 px-3 py-1">
                  <CheckCircle2 className="h-3 w-3 text-amber-300" />
                  Seguimiento mensual
                </span>
                <span className="inline-flex items-center gap-1.5 rounded-full bg-white/5 border border-white/10 px-3 py-1">
                  <CheckCircle2 className="h-3 w-3 text-amber-300" />
                  100% transparente
                </span>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ────────── HOW IT WORKS ────────── */}
      <section className="relative py-20">
        <div className="container mx-auto px-4 max-w-5xl">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-3xl md:text-5xl font-bold text-center mb-14 tracking-tight"
          >
            ¿Cómo funciona?
          </motion.h2>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            {[
              { n: '1', title: 'Contáctanos', desc: 'Escríbenos por WhatsApp y elige cuántos árboles donar.' },
              { n: '2', title: 'Dona', desc: 'Realiza tu aporte de forma segura con los métodos disponibles.' },
              { n: '3', title: 'Sembramos', desc: 'Nuestro equipo siembra tu árbol en la Ciénaga de Barbacoas.' },
              { n: '4', title: 'Sigue el crecimiento', desc: 'Recibes fotos y actualizaciones del progreso.' },
            ].map((s, i) => (
              <motion.div
                key={s.n}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                className="relative rounded-3xl bg-emerald-900/40 border border-emerald-400/20 p-6"
              >
                <div className="absolute -top-4 left-6 h-10 w-10 rounded-full bg-gradient-to-br from-amber-400 to-amber-600 flex items-center justify-center text-emerald-950 text-lg font-black shadow-lg">
                  {s.n}
                </div>
                <h3 className="text-lg font-bold mt-4 mb-2 text-white">{s.title}</h3>
                <p className="text-sm text-emerald-100/80 leading-relaxed">{s.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ────────── FINAL CTA ────────── */}
      <section className="relative py-20 bg-gradient-to-t from-black to-emerald-950 border-t border-emerald-800/50">
        <div className="container mx-auto px-4 text-center max-w-3xl">
          <Users className="h-10 w-10 text-amber-400 mx-auto mb-4" />
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Únete a la comunidad que está<br />
            <span className="text-amber-300">restaurando Colombia</span>
          </h2>
          <p className="text-emerald-100 mb-8">
            Juntos podemos proteger uno de los humedales más importantes del país. Tu árbol es
            para siempre. Su historia, también.
          </p>
          <div className="flex flex-wrap justify-center gap-3 mb-8">
            <a href={whatsappLink(PHONES[0].raw)} target="_blank" rel="noopener noreferrer">
              <button className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-amber-500 to-amber-400 text-emerald-950 font-black px-8 py-3 text-sm shadow-lg shadow-amber-500/30 hover:scale-105 transition">
                <Phone className="h-4 w-4" />
                Donar ahora
              </button>
            </a>
            <button
              onClick={share}
              className="inline-flex items-center gap-2 rounded-full bg-white/10 hover:bg-white/20 border border-white/20 text-white font-semibold px-6 py-3 text-sm transition"
            >
              {copied ? <CheckCircle2 className="h-4 w-4" /> : <Share2 className="h-4 w-4" />}
              {copied ? '¡Enlace copiado!' : 'Compartir con amigos'}
            </button>
          </div>

          {/* Social */}
          <div className="flex justify-center gap-3 text-emerald-200/60 text-xs">
            <span>🌱 Siembra · Crece · Protege 🌱</span>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 border-t border-emerald-800/50 text-center text-[11px] text-emerald-300/60">
        <p>© {new Date().getFullYear()} Gran Donatón Ambiental · Ciénaga Barbacoas</p>
        <p className="mt-1">Yondó, Antioquia · Colombia 🇨🇴</p>
      </footer>

      {/* Floating WhatsApp button */}
      <a
        href={whatsappLink(PHONES[0].raw)}
        target="_blank"
        rel="noopener noreferrer"
        className="fixed bottom-6 right-6 z-50 flex items-center gap-2 rounded-full bg-green-500 hover:bg-green-600 text-white font-bold px-5 py-3 shadow-2xl shadow-green-900/50 transition-all hover:scale-105 group"
        aria-label="Contactar por WhatsApp"
      >
        <MessageCircle className="h-5 w-5" />
        <span className="hidden sm:inline text-sm">Donar ahora</span>
        <span className="absolute inset-0 rounded-full animate-ping bg-green-400/40 -z-10" />
      </a>

      <button
        onClick={() => {
          const url = whatsappLink(PHONES[0].raw);
          try {
            navigator.clipboard?.writeText(url);
          } catch { /* ignore */ }
        }}
        className="hidden"
        aria-hidden
      >
        <Copy className="h-3 w-3" />
      </button>
    </div>
  );
}
